export {
  COMMUNICATION_DISPLAY_MAX_MHZ as DISPLAY_FREQUENCY_MAX_MHZ,
  COMMUNICATION_DISPLAY_MIN_MHZ as DISPLAY_FREQUENCY_MIN_MHZ,
  COMMUNICATION_EMERGENCY_FREQUENCY_MHZ as EMERGENCY_FREQUENCY_MHZ,
  isDisplayedCommunicationFrequency,
} from '../../calculations/communicationFrequencySelection';
